---
- name: Download WebStorm Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/webstorm/WebStorm-{{javascript_webstorm_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/webstorm-{{javascript_webstorm_version}}.tar.gz"
      mode: 0444
  when: javascript_webstorm_install

- name: Uncompress WebStorm Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/webstorm-{{javascript_webstorm_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_software_directory}}/WebStorm-{{javascript_webstorm_build}}/build.txt"
  when: javascript_webstorm_install

- name: Create Softlink To WebStorm
  become: no
  file:
      src: "{{ansible_user_dir}}/{{base_software_directory}}/WebStorm-{{javascript_webstorm_build}}"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/webstorm"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: javascript_webstorm_install

- name: Create Desktop Icon For WebStorm
  become: no
  template:
      src: "templates/webstorm.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/webstorm.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0755
  when: javascript_webstorm_install

- name: Set Global Environment To Have WebStorm Use Shared JDK
  become: yes
  template:
      src: "templates/webstorm-environment.sh.j2"
      dest: "/etc/profile.d/webstorm-environment.sh"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
  when: javascript_webstorm_share_jdk

- name: Remove WebStorm's Embedded JDK
  become: no
  file:
      path: "{{ansible_user_dir}}/{{base_software_directory}}/webstorm/jre64"
      state: absent
  when: javascript_webstorm_share_jdk

# - "generator-jhipster"

- name: Update global NPM packages
  become: yes
  npm:
      name: "{{item}}"
      global: yes
      state: present
  with_items:
  - "yo"
  - "bower"
  - "grunt-cli"
  - "gulp-cli"
  - "serverless"
